### ISSUE TITLE
MPI update

### ISSUE THREAD

**Issue by DiffeoInvariant** [dlchao/FluTE#3]
Hi @dlchao, figured I'd let you know that I updated the MPI calls in mpiflute to be correct for MPI 3.0 (which deprecates the C++ API, among other minor changes) in my local version. It appears that I don't have permission to push to a development branch, but if you're interested in the updated mpiflute code, let me know and we can sort out a pull request.

**Comment by dlchao** [comment]
@DiffeoInvariant Could you send me a pull request, and I'll take a look at your changes and merge them if they work on my machine. Thanks for your help!

**Comment by DiffeoInvariant** [comment]
Done--you're welcome! Thank you for helping me get things working initially! We're planning to run a bunch of data assimilation algorithms on FluTE (and other epidemiological models as they become available) with COVID-19 data, so if you're interested in our results, I can shoot you an email when we have something.
